# process an image to detect objects
Header header
# either provide an image or an image topic
sensor_msgs/CompressedImage image
string image_topic
uint16 max_detections
float32 min_threshold
---
Header header
float32[] scores
string[] class_names
uint16[] class_ids
# location of object box in image in pixels
uint16[] xmin
uint16[] ymin
uint16[] xmax
uint16[] ymax
